# Generated by Django 4.2.4 on 2024-01-10 02:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "item",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("amount_on_hand", models.IntegerField(default=0)),
                ("unit_measure", models.CharField(max_length=50)),
                ("cost_uom", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Menue_Item",
            fields=[
                (
                    "entree",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("price", models.FloatField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "transaction_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("total_amount", models.FloatField()),
                ("dt", models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name="SalesLines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entree",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pizzaman.inventory",
                    ),
                ),
                (
                    "transaction_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pizzaman.sales"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe_list",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_amount_used", models.FloatField()),
                (
                    "entree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizzaman.menue_item",
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pizzaman.inventory",
                    ),
                ),
            ],
        ),
    ]
