# Generated by Django 4.2.4 on 2024-01-11 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pizzaman", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menue_Item",
            new_name="MenueItem",
        ),
    ]
