# Generated by Django 4.2.4 on 2024-01-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzaman", "0002_rename_menue_item_menueitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleslines",
            name="id",
        ),
        migrations.AddField(
            model_name="saleslines",
            name="line_id",
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="saleslines",
            name="qty",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="sales",
            name="transaction_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
