# Generated by Django 4.2.4 on 2024-01-13 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pizzaman", "0004_sales_status_alter_sales_dt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sales",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="saleslines",
            name="entree",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pizzaman.menueitem",
            ),
        ),
    ]
