# Generated by Django 4.2.4 on 2024-01-14 04:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzaman", "0005_alter_sales_total_amount_alter_saleslines_entree"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sales",
            old_name="dt",
            new_name="created_dt",
        ),
    ]
